---
owner: hostwithquantum
repo: status.planetary-quantum.com

assignees:
  - till
  - rwos

sites:
  - name: Console
    url: https://console.planetary-quantum.com/
  - name: Managed Logging
    url: https://logs.planetary-quantum.com/
    expectedStatusCodes:
      - 403
  - name: Managed Metrics
    url: https://metrics.planetary-quantum.com/
    expectedStatusCodes:
      - 404
  - name: Managed Registry
    url: https://r.planetary-quantum.com/
  - name: quantum-cli
    url: https://cli.planetary-quantum.com/
  - name: Quantum ID
    url: https://id.planetary-quantum.com/
  - name: Documentation
    url: https://docs.planetary-quantum.com/
  - name: Website
    url: https://www.planetary-quantum.com/
  - name: Object Storage
    url: https://s3.storage.planetary-networks.de/
    expectedStatusCodes:
      - 403

status-website:
  theme: ocean
  cname: status.planetary-quantum.com
  logoUrl: https://www.planetary-quantum.com/wp-content/uploads/2021/04/logo_white.svg
  name: Status Page
  introTitle: ""
  introMessage: "We provide customers with an application hosting platform (on top of Docker Swarm). To learn more about what we are monitoring, feel free to check out [our platform documentation](https://docs.planetary-quantum.com/platform/)."
  navbar:
    - title: Website
      href: https://www.planetary-quantum.com/
    - title: Imprint / Impressum
      href: https://www.planetary-quantum.com/service/impressum/
    - title: Subscribe via GitHub
      href: https://github.com/$OWNER/$REPO
